
services:
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
      # TODO: Add gpu support
    # environment:
    #   - gpus=all
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]    

  chatbot:
    build: .
    ports:
      - "8501:8501"
    environment:
      - OLLAMA_HOST=http://ollama:11434
    volumes:
      - ./bible_vectorstore:/app/bible_vectorstore
    depends_on:
      - ollama

volumes:
  ollama_data:
  bible_vectorstore: